apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bladerf-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: bladerf-device-plugin
  template:
    metadata:
      labels:
        name: bladerf-device-plugin
    spec:
      tolerations:
        - operator: "Exists"
          effect: "NoExecute"
        - operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: bladerf-device-plugin
          image: localhost:5000/apurer/bladerf-device-plugin:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
