apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bladerf-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: bladerf-device-plugin
  template:
    metadata:
      labels:
        name: bladerf-device-plugin
    spec:
      tolerations:
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
      containers:
      - image: apurer/bladerf-device-plugin:latest
        name: bladerf-device-plugin
        securityContext:
          privileged: true
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      tolerations:
      - operator: Exists
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
